require 'sinatra'
require 'faraday'
require 'sinatra/json'
require './serializers/state_stats_serializer'
require './serializers/national_stats_serializer'
require './poros/state_stats'
require './poros/national_stats'
